#!/usr/bin/python3
"""
Module 101-locked_class
"""


class Frozen(object):
    __attributes = 'first_name'
    def __setattr__(self, key, value):
        if key != type(self).__attributes:
            raise AttributeError("'{}' object has no attribute"
                                 "'{}'".format(self.__name__, key))
        else:
            object.__setattr__(self, key, value)


class LockedClass(Frozen):
    def __init__(self):
        self.first_name = 'name'
